# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml GO THROUGH
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$cloud-init-248919/terraform', '.']
- name: 'gcr.io/cloud-init-248919/terraform'
  args: ['version']
images: ['gcr.io/cloud-init-248919/terraform']
tags: ['cloud-builders-community']
